### ISSUE TITLE
Về phần Docs

### ISSUE THREAD

**Issue by khiem1703** [khiem1703/SE-04-Nhom6.1#5]
bạn làm docs nhanh chóng push lên để mọi người xem nhé

**Comment by DoNgoc47** [comment]
làm nhanh nhé ae 2/1 nộp rồi đó.

**Comment by khiem1703** [comment]
uầy có cả biểu tượng cảm xúc ae ạ ,mới phát hiện r

**Comment by ntthanh25** [comment]
OK t đã hoàn thành rồi

**Comment by Trananh3199** [comment]
t đọc thấy ổn rồi ,mọi người kiểm tra lại xem

**Comment by NgoThien963** [comment]
mình thấy vẫn còn 1 số lỗi trình bày, các bạn căn chỉnh lại cho đúng tiêu chuẩn nhá

**Comment by DoNgoc47** [comment]
uk t cũng thấy vậy ó.
