### ISSUE TITLE
xóa category bất kỳ.

### ISSUE THREAD

**Issue by DoNgoc47** [khiem1703/SE-04-Nhom6.1#7]

**Comment by DoNgoc47** [comment]
mỗi cái category này  liên kết với 1 đống cái products . nếu muốn xóa 1 cái category thì t chưa tìm đc hướng làm ntn

**Comment by Trananh3199** [comment]
Xóa hết cả 1 đống sp , dễ lỗi ý

**Comment by NgoThien963** [comment]
ko thì chỉ xóa cái category đấy thôi
ko động đến những cái  products kia á

**Comment by DoNgoc47** [comment]
tại vì 2 cái bảng category và products có liên kết 1-n với nhau xóa đi hơi rắc rối

**Comment by DoNgoc47** [comment]
chắc làm như ánh. xóa hết sản phẩm trong bảng products có id_category cần xóa. sau đó xóa đến category
