### ISSUE TITLE
T thấy giao diện chưa ổn lắm một số vẫn thiếu link.

### ISSUE THREAD

**Issue by DoNgoc47** [khiem1703/SE-04-Nhom6.1#8]

**Comment by ntthanh25** [comment]
T cũng thấy thiếu link phần sản phẩm (lọc sản phẩm theo danh mục)

**Comment by DoNgoc47** [comment]
uk t cũng mới thấy vậy. Để nhờ khiêm fix .

**Comment by Trananh3199** [comment]
Fix nốt để xong là ổn

**Comment by NgoThien963** [comment]
mấy cái quay lại trang chủ hay mấy hình ảnh đều bị thiếu link á

**Comment by NgoThien963** [comment]
chúng ta nên fix lại toàn bộ để tránh thiếu xót

**Comment by DoNgoc47** [comment]
uk mấy cái về quyên chưa add thêm link thì t cũng có nhờ ánh tìm. Mn hỏi ảnh và thêm link vào chỗ thiếu nhá.
